export interface CountryData {
  nameEn: string;
  nameAr: string;
  code: string;
  dialCode: string;
  phoneMask: string;
  phoneExample: string;
  phoneRegex: string;
}

export const countriesData: CountryData[] = [
  {
    nameEn: "Saudi Arabia",
    nameAr: "السعودية",
    code: "sa",
    dialCode: "+966",
    phoneMask: "## ### ####",
    phoneExample: " Example: 51 234 5678",
    phoneRegex: "^5\\d{8}$",
  },
  {
    nameEn: "UAE",
    nameAr: "الإمارات",
    code: "ae",
    dialCode: "+971",
    phoneMask: "## ### ####",
    phoneExample: " Example: 50 123 4567",
    phoneRegex: "^5\\d{8}$",
  },
  {
    nameEn: "Egypt",
    nameAr: "مصر",
    code: "eg",
    dialCode: "+20",
    phoneMask: "### ### ####",
    phoneExample: " Example: 102 378 0008",
    phoneRegex: "^1[0125]\\d{8}$",
  },
  {
    nameEn: "Jordan",
    nameAr: "الأردن",
    code: "jo",
    dialCode: "+962",
    phoneMask: "# #### ####",
    phoneExample: " Example: 7 9123 4567",
    phoneRegex: "^7[789]\\d{7}$",
  },
  {
    nameEn: "Kuwait",
    nameAr: "الكويت",
    code: "kw",
    dialCode: "+965",
    phoneMask: "#### ####",
    phoneExample: " Example: 5123 4567",
    phoneRegex: "^[569]\\d{7}$",
  },
  {
    nameEn: "Bahrain",
    nameAr: "البحرين",
    code: "bh",
    dialCode: "+973",
    phoneMask: "#### ####",
    phoneExample: " Example: 3600 1234",
    phoneRegex: "^3[2-9]\\d{6}$",
  },
  {
    nameEn: "Oman",
    nameAr: "عُمان",
    code: "om",
    dialCode: "+968",
    phoneMask: "#### ####",
    phoneExample: " Example: 9212 3456",
    phoneRegex: "^[79]\\d{7}$",
  },
  {
    nameEn: "Qatar",
    nameAr: "قطر",
    code: "qa",
    dialCode: "+974",
    phoneMask: "#### ####",
    phoneExample: " Example: 5512 3456",
    phoneRegex: "^[3-7]\\d{7}$",
  },
  {
    nameEn: "Iraq",
    nameAr: "العراق",
    code: "iq",
    dialCode: "+964",
    phoneMask: "### ### ####",
    phoneExample: " Example: 771 234 5678",
    phoneRegex: "^7[3-9]\\d{8}$",
  },
  {
    nameEn: "Lebanon",
    nameAr: "لبنان",
    code: "lb",
    dialCode: "+961",
    phoneMask: "## ### ###",
    phoneExample: " Example: 71 123 456",
    phoneRegex: "^[378]\\d{7}$",
  },
  {
    nameEn: "Morocco",
    nameAr: "المغرب",
    code: "ma",
    dialCode: "+212",
    phoneMask: "## ### ####",
    phoneExample: " Example: 61 234 5678",
    phoneRegex: "^[5-7]\\d{8}$",
  },
  {
    nameEn: "Tunisia",
    nameAr: "تونس",
    code: "tn",
    dialCode: "+216",
    phoneMask: "## ### ###",
    phoneExample: " Example: 20 123 456",
    phoneRegex: "^[2-9]\\d{7}$",
  },
  {
    nameEn: "Algeria",
    nameAr: "الجزائر",
    code: "dz",
    dialCode: "+213",
    phoneMask: "### ## ## ##",
    phoneExample: " Example: 551 23 45 67",
    phoneRegex: "^[5-7]\\d{8}$",
  },
  {
    nameEn: "United States",
    nameAr: "الولايات المتحدة",
    code: "us",
    dialCode: "+1",
    phoneMask: "(###) ###-####",
    phoneExample: " Example: (201) 555-0123",
    phoneRegex: "^[2-9]\\d{9}$",
  },
  {
    nameEn: "United Kingdom",
    nameAr: "المملكة المتحدة",
    code: "gb",
    dialCode: "+44",
    phoneMask: "#### ######",
    phoneExample: " Example: 7911 123456",
    phoneRegex: "^7\\d{9}$",
  },
];
